### ISSUE TITLE
Equation not rendered

### ISSUE THREAD

**Issue by GTP95** [phillord/mathjax-latex#57]
Greetings,

I'm trying to use this plugin on WordPress 6.1.1, but I can't get it to work. This is how I typed two equations into the block editor:
![MathJax-LaTex](https://user-images.githubusercontent.com/9197945/212501606-9ee9f295-b4c5-4486-b06d-25efb41fc3b9.png)

And this is what I see in WordPress' preview:
![rendered](https://user-images.githubusercontent.com/9197945/212501660-351bbffc-8f8c-4cf6-a03a-f891866e1048.png)

My browser is the latest version of Firefox, what am I doing wrong?

**Comment by paulschreiber** [comment]
1. There's not enough information given to diagnose or solve your problem.
2. Is this on a public web page? That will help people debug.
3. The issue tracker is not a support forum.

**Comment by GTP95** [comment]
1. Which additional info would you like to have?2. No, but I can publish a test page if that helps.3. If you'd rather have me ask this on a forum, where could I get help with this plug-in?
-------- Messaggio originale --------Da: Paul Schreiber ***@***.***> Data: 15/01/23  00:39  (GMT+01:00) A: phillord/mathjax-latex ***@***.***> Cc: Giacomo Tommaso Petrucci ***@***.***>, Author ***@***.***> Oggetto: Re: [phillord/mathjax-latex] Equation not rendered (Issue #57) 

There's not enough information given to diagnose or solve your problem.
Is this on a public web page? That will help people debug.
The issue tracker is not a support forum.

**Comment by GTP95** [comment]
Regarding 2, I published a test page [here](https://crypto.gtpware.eu/mathjax-latex-test-page/) where I copied and pasted the code given in the readme inside the block editor:
```
[latex]E=mc^2[/latex]
```
Please let me know about points 1 and 3.
Regards,

GTP95

**Comment by paulschreiber** [comment]
1.
(a) The text in your original post is a screen shot. Had you posted editable text, it would have been less work for people trying to help you to copy and paste and reproduced.

(b) The JS URL you are using is
```
https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js?config&#038;ver=1.3.11
```

(c) The console shows this error:
```
Uncaught TypeError: this.params.config.split is not a function
```
In your case, `this.params.config` is set to `true` instead of a string value.

To fix this, go to Settings > MathJax-LaTeX; click Save Changes. This should force "default" to be saved as the configuration which should fix the problem.

**Comment by GTP95** [comment]
Thank you for the tip. I did as you said and now the page is showing the equation, but it is still not rendered correctly: it appears as `\(E=mc^2\)`. This is probably related to (b), I have the default setting "Use MathJax CDN Service" enabled, is the URL I'm using the correct one? 
I tried to force a different one by specifying `https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/startup.js` in the "Custom MatJax location field, but it didn't solve the issue.
(I found the new URL [here](https://cdnjs.com/libraries/mathjax)).

**Comment by paulschreiber** [comment]
@GTP95 Did you include the `[mathjax]` shortcode on your page?

Mathjax 3.x is incompatible with with 2.x and has not been tested with this plugin. I have no idea if that will work.

**Comment by GTP95** [comment]
I didn't include it, as my understanding of what's written inside the readme was that it is not necessary. But adding it didn't change anything. This is what I typed inside the block editor:
```
[mathjax]

[latex]E=mc^2[/latex]
```
As for the MathJax version, I double-checked that the option "Use MathJax CDN Service" is enabled in the settings, so it should be the correct version.

**Comment by paulschreiber** [comment]
Please share a screen shot of your MathJax-LaTeX settings page.

**Comment by GTP95** [comment]
No, that's exactly what I have written in the code editor, as I reported [here](https://github.com/phillord/mathjax-latex/issues/57#issuecomment-1385434227). And [here](https://crypto.gtpware.eu/mathjax-latex-test-page/) is how it gets rendered. Here is a screenshot of how I see the code inside the block editor:
![block editor](https://user-images.githubusercontent.com/9197945/212940883-c3d9cba7-4956-488b-ad6d-89283dc32ad7.png)

**Comment by paulschreiber** [comment]
Something else is amiss. Those parentheses aren't writing themselves. Try deleting this page and making a new one.

**Comment by GTP95** [comment]
Still not working. I have no idea why this plugin didn't work for me, but in the end I just gave up and installed the [Simple MathJax](https://github.com/boolesrings/Simple-Mathjax-wordpress-plugin) plugin, which for me worked out of the box even if it is untested on the latest version of Wordpress. If anyone else is struggling with the same issue, it's probably faster to just switch plugins instead of trying to debug it.
Thank you anyway for your help,

GTP95
